export const universities = [
  {
    name: "California Polytechnic University, Pomona",
    id: 75,
  },
  {
    name: "California Polytechnic University, San Luis Obispo",
    id: 11,
  },
  {
    name: "California State University, Bakersfield",
    id: 98,
  },
  {
    name: "California State University, Channel Islands",
    id: 143,
  },
  {
    name: "California State University, Chico",
    id: 141,
  },
  /*
  // does not work with 24-25, but works with 23-24
  {
    name: "California State University, Dominguez Hills",
    id: 50,
  },
  */
  {
    name: "California State University, East Bay",
    id: 21,
  },
  {
    name: "California State University, Fresno",
    id: 29,
  },
  {
    name: "California State University, Fullerton",
    id: 129,
  },
  {
    name: "California State University, Long Beach",
    id: 81,
  },
  {
    name: "California State University, Los Angeles",
    id: 76,
  },
  {
    name: "California State University, Monterey Bay",
    id: 12,
  },
  {
    name: "California State University, Northridge",
    id: 42,
  },
  {
    name: "California State University, Sacramento",
    id: 60,
  },
  {
    name: "California State University, Stanislaus",
    id: 24,
  },
  {
    name: "San Francisco State University",
    id: 116,
  },
  {
    name: "San Jose State University",
    id: 39,
  },
  /*
  // does not work with 24-25. works with 23-24
  {
    name: "Sonoma State University",
    id: 88,
  },
  */
  {
    name: "University of California, Berkeley",
    id: 79,
  },
  {
    name: "University of California, Davis",
    id: 89,
  },
  {
    name: "University of California, Irvine",
    id: 120,
  },
  {
    name: "University of California, Los Angeles",
    id: 117,
  },
  {
    name: "University of California, Merced",
    id: 144,
  },
  {
    name: "University of California, Riverside",
    id: 46,
  },
  {
    name: "University of California, San Diego",
    id: 7,
  },
  {
    name: "University of California, Santa Barbara",
    id: 128,
  },
  {
    name: "University of California, Santa Cruz",
    id: 132,
  },
];

export const caliCCs = [
  { name: "Allan Hancock College", id: 110 },
  { name: "American River College", id: 27 },
  { name: "Antelope Valley College", id: 121 },
  { name: "Bakersfield College", id: 84 },
  { name: "Barstow Community College", id: 20 },
  { name: "Berkeley City College", id: 58 },
  { name: "Butte College", id: 8 },
  { name: "Cabrillo College", id: 41 },
  { name: "Canada College", id: 68 },
  { name: "Cerritos College", id: 104 },
  { name: "Cerro Coso Community College", id: 9 },
  { name: "Chabot College", id: 96 },
  { name: "Chaffey College", id: 69 },
  { name: "Citrus College", id: 97 },
  { name: "City College of San Francisco", id: 33 },
  { name: "Clovis Community College", id: 150 },
  { name: "Coalinga College", id: 67 },
  { name: "Coastline Community College", id: 105 },
  { name: "College of Alameda", id: 111 },
  { name: "College of Marin", id: 4 },
  { name: "College of San Mateo", id: 5 },
  { name: "College of the Canyons", id: 140 },
  { name: "College of the Desert", id: 30 },
  { name: "College of the Redwoods", id: 83 },
  { name: "College of the Sequoias", id: 6 },
  { name: "College of the Siskiyous", id: 102 },
  { name: "Columbia College", id: 10 },
  { name: "Compton College", id: 34 },
  { name: "Contra Costa College", id: 28 },
  { name: "Copper Mountain College", id: 112 },
  { name: "Cosumnes River College", id: 142 },
  { name: "Crafton Hills College", id: 70 },
  { name: "Cuesta College", id: 16 },
  { name: "Cuyamaca College", id: 99 },
  { name: "Cypress College", id: 71 },
  { name: "De Anza College", id: 113 },
  { name: "Diablo Valley College", id: 114 },
  { name: "East Los Angeles College", id: 118 },
  { name: "El Camino College", id: 103 },
  { name: "El Camino College", id: 153 },
  { name: "Evergreen Valley College", id: 2 },
  { name: "Feather River College", id: 122 },
  { name: "Folsom Lake College", id: 145 },
  { name: "Foothill College", id: 51 },
  { name: "Fresno City College", id: 35 },
  { name: "Fullerton College", id: 134 },
  { name: "Gavilan College", id: 72 },
  { name: "Glendale Community College", id: 43 },
  { name: "Golden West College", id: 55 },
  { name: "Grossmont College", id: 106 },
  { name: "Hartnell College", id: 123 },
  { name: "Imperial Valley College", id: 107 },
  { name: "Irvine Valley College", id: 124 },
  { name: "Lake Tahoe Community College", id: 40 },
  { name: "Laney College", id: 77 },
  { name: "Las Positas College", id: 18 },
  { name: "Lassen Community College", id: 82 },
  { name: "Lemoore College", id: 146 },
  { name: "Long Beach City College", id: 135 },
  { name: "Los Angeles City College", id: 3 },
  { name: "Los Angeles Harbor College", id: 31 },
  { name: "Los Angeles Mission College", id: 47 },
  { name: "Los Angeles Pierce College", id: 86 },
  { name: "Los Angeles Southwest College", id: 130 },
  { name: "Los Angeles Trade Technical College", id: 25 },
  { name: "Los Angeles Valley College", id: 44 },
  { name: "Los Medanos College", id: 61 },
  { name: "Madera Community College", id: 200 },
  { name: "Mendocino College", id: 100 },
  { name: "Merced College", id: 17 },
  { name: "Merritt College", id: 13 },
  { name: "MiraCosta College", id: 108 },
  { name: "Mission College", id: 32 },
  { name: "Modesto Junior College", id: 52 },
  { name: "Monterey Peninsula College", id: 133 },
  { name: "Moorpark College", id: 139 },
  { name: "Moreno Valley College", id: 149 },
  { name: "Mount San Antonio College", id: 62 },
  { name: "Mt. San Jacinto College", id: 53 },
  { name: "Napa Valley College", id: 73 },
  { name: "Norco College", id: 148 },
  { name: "Ohlone College", id: 48 },
  { name: "Orange Coast College", id: 74 },
  { name: "Oxnard College", id: 87 },
  { name: "Palo Verde College", id: 63 },
  { name: "Palomar College", id: 56 },
  { name: "Pasadena City College", id: 49 },
  { name: "Porterville College", id: 125 },
  { name: "Reedley College", id: 36 },
  { name: "Rio Hondo College", id: 64 },
  { name: "Riverside City College", id: 78 },
  { name: "Sacramento City College", id: 126 },
  { name: "Saddleback College", id: 65 },
  { name: "San Bernardino Valley College", id: 131 },
  { name: "San Diego City College", id: 54 },
  { name: "San Diego Mesa College", id: 101 },
  { name: "San Diego Miramar College", id: 45 },
  { name: "San Joaquin Delta College", id: 109 },
  { name: "San Jose City College", id: 136 },
  { name: "Santa Ana College", id: 14 },
  { name: "Santa Barbara City College", id: 92 },
  { name: "Santa Monica College", id: 137 },
  { name: "Santa Rosa Junior College", id: 57 },
  { name: "Santiago Canyon College", id: 66 },
  { name: "Shasta College", id: 38 },
  { name: "Sierra College", id: 93 },
  { name: "Skyline College", id: 127 },
  { name: "Solano Community College", id: 94 },
  { name: "Southwestern College", id: 138 },
  { name: "Taft College", id: 119 },
  { name: "Ventura College", id: 95 },
  { name: "Victor Valley College", id: 19 },
  { name: "West Los Angeles College", id: 91 },
  { name: "West Valley College", id: 80 },
  { name: "Woodland Community College", id: 147 },
  { name: "Yuba College", id: 90 },
];
